#!/bin/bash

# Installazione delle dipendenze del progetto
echo "Installazione delle dipendenze del progetto..."

# Installa le dipendenze specificate nel file go.mod
go mod tidy

echo "Installazione completata!"

docker build -t coraza-waf  .
