#!/bin/bash

# Nome dei file per le chiavi
PRIVATE_KEY_FILE="private.pem"
PUBLIC_KEY_FILE="public.pem"

openssl ecparam -name secp521r1 -genkey -noout -out $PRIVATE_KEY_FILE

openssl ec -in $PRIVATE_KEY_FILE -pubout -out $PUBLIC_KEY_FILE

cp $PUBLIC_KEY_FILE ../resource_server/
cp $PUBLIC_KEY_FILE ../otp_server/
fi
